CREATE TABLE IF NOT EXISTS tracks (
    Id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    IdArtist INTEGER NOT NULL DEFAULT 1,
    title TEXT NOT NULL ,
    duration INTEGER NOT NULL DEFAULT 120,
    year INTEGER NOT NULL DEFAULT 2015
);

